name: Influx
favicon: null
layout_spectrum: 0.003155834972858429
typography_spectrum: 0.6689706889446825
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.4174045247491449
  lightness: 0.6053691040724516
  saturation: 0.2557159950956702
  rhythmicContrast: 0.5427821145858616
purpose: []
